[package]
name = "antipixel"
version = "0.1.0"
authors = ["Taha-Firoz <i170323@nu.edu.pk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
